version: '3'

services:

    # indexing-engine:
    #     build: ./indexer-engine
    #     restart: always
    #     ports:
    #         - "3001:3000"
    #     volumes:
    #         - ./indexer-engine:/app
    #         - /home/dev/go:/go:ro
    #     command: ["indexer-engine", "--grpc", "5000"]

    # indexing-srv:
    #     build: ./indexer-srv
    #     restart: always
    #     ports:
    #         - "3002:3000"
    #     volumes:
    #         - ./indexer-engine:/app
    #         - /home/dev/go:/go:ro
    #     command: ["indexer-engine", "--grpc", "5000"]

    clickhouse-zookeeper:
        image: zookeeper:3.8
        hostname: clickhouse-zookeeper
        ports:
            - "2181:2181"
            - "2182:2182"

    clickhouse:
        image: yandex/clickhouse-server:21.3
        hostname: clickhouse
        ports:
            - 9001:9000
            - 8123:8123 # => ...:8123/play
        # volumes:
        #         - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
        #         - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
        #         - ./config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
        #         - ./config/users.xml:/etc/clickhouse-server/users.xml
        #         # - ./data/server-01:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"
