
database:
  type: clickhouse
  uri: tcp://clickhouse:9000?database=app
  name: indexer

server:
  env: development
  host: "0.0.0.0"
  port: 3000
  cron_job_interval: 60
  network: ethereum
  tatum_api_token: b211febc-6e35-4430-959d-9ae103799f4b
  number_of_block_for_capturing: 5
  authentication_plugin: keyclock